### ISSUE TITLE
Migrate Flutter V2 problem.

### ISSUE THREAD

**Issue by yamisagi** [DetainedDeveloper/App-Brewery-Flutter-Null-Safety#2]
### All we know Course materials are out-dated

To fix this issue easily , 
Delete all files and folders in App folder **except** couse materials **lib folder-Assets-Fonts-pubspec.yaml**

For Example;
 
![ww](https://user-images.githubusercontent.com/84624853/151516481-b0eb6102-215c-4cf7-9774-fccffc2e9245.jpg)

and then go to Terminal while its in project folder and
**write this line to Terminal**
`flutter create .`

For Example;

![crate](https://user-images.githubusercontent.com/84624853/151516510-ae00c14b-5d79-42fc-9801-3dc9c822bfe4.jpg)

**And then Flutter starts rebuilding application with migrated version of it.**

Hope this works.

**Comment by DetainedDeveloper** [comment]
@yamisagi You've done a good job, Thanks! I will surely add this to repository and mention you as well.
I've enabled Discussions, can you start a discussion and delete the issue? Since it's an add on and not an actual issue.

**Comment by yamisagi** [comment]
Thank you.

**Comment by DetainedDeveloper** [comment]
@yamisagi Can you please send a pull request with this so you automatically get added as a contributor?

**Comment by DetainedDeveloper** [comment]
@yamisagi I suggest you take pull of the latest version before sending a pull request, thanks.

**Comment by yamisagi** [comment]
> @yamisagi I suggest you take pull of the latest version before sending a pull request, thanks.

Hi, updated content and created pull request, you can control it 😊
